name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      matrix:
        tap:
          - "ohakutsu/font-zutomayo"
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - run: brew readall '${{ matrix.tap }}'
      - run: brew style --cask '${{ matrix.tap }}'
      - run: brew audit --strict --cask --tap '${{ matrix.tap }}'
      - run: brew install --cask --verbose "$(echo '${{ matrix.tap }}' | awk -F '/' '{print $2}')"
